{{- range $key, $value := .Values }}
{{- if and (ne $key "global") (ne $key "replicaCount") (ne $key "resources") (ne $key "ingress") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  labels:
    app: {{ $.Release.Name }}
    component: {{ $key }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
      component: {{ $key }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        component: {{ $key }}
    spec:
      containers:
        - name: {{ $key }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $value.port }}
          
          # Injection des variables d'environnement si définies dans values.yaml
          {{- if $value.env }}
          env:
            {{- range $envName, $envValue := $value.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
            {{- end }}
          {{- end }}

          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
{{- end }}
{{- end }}