apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          # IMPORTANT : /api avant / sinon tout est capturé par le frontend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway
                port:
                  number: {{ .Values.gateway.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.port }}