apiVersion: networking.k8s.io/v1
kind: Ingress
meta
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    # Frontend accessible à la racine http://<IP>
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
    
    # API Gateway accessible via http://<IP>/api
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-gateway
                port:
                  number: {{ .Values.gateway.port }}