{{- range $key, $value := .Values }}
{{- if and (ne $key "global") (ne $key "replicaCount") (ne $key "resources") (ne $key "ingress") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Release.Name }}
    component: {{ $key }}
  ports:
    - protocol: TCP
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
{{- end }}
{{- end }}